//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.OacIntegrationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Appointment", Namespace="http://schemas.datacontract.org/2004/07/Oac.IntegrationService.Contracts.Data")]
    [System.SerializableAttribute()]
    public partial class Appointment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppointmentDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AppointmentDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssignedUserCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssignedUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConfirmationNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> DurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppointmentDate {
            get {
                return this.AppointmentDateField;
            }
            set {
                if ((object.ReferenceEquals(this.AppointmentDateField, value) != true)) {
                    this.AppointmentDateField = value;
                    this.RaisePropertyChanged("AppointmentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AppointmentDateTime {
            get {
                return this.AppointmentDateTimeField;
            }
            set {
                if ((this.AppointmentDateTimeField.Equals(value) != true)) {
                    this.AppointmentDateTimeField = value;
                    this.RaisePropertyChanged("AppointmentDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssignedUserCode {
            get {
                return this.AssignedUserCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AssignedUserCodeField, value) != true)) {
                    this.AssignedUserCodeField = value;
                    this.RaisePropertyChanged("AssignedUserCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssignedUsername {
            get {
                return this.AssignedUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.AssignedUsernameField, value) != true)) {
                    this.AssignedUsernameField = value;
                    this.RaisePropertyChanged("AssignedUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConfirmationNumber {
            get {
                return this.ConfirmationNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfirmationNumberField, value) != true)) {
                    this.ConfirmationNumberField = value;
                    this.RaisePropertyChanged("ConfirmationNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((this.DurationField.Equals(value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationCode {
            get {
                return this.LocationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationCodeField, value) != true)) {
                    this.LocationCodeField = value;
                    this.RaisePropertyChanged("LocationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationName {
            get {
                return this.LocationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationNameField, value) != true)) {
                    this.LocationNameField = value;
                    this.RaisePropertyChanged("LocationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceCode {
            get {
                return this.ServiceCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceCodeField, value) != true)) {
                    this.ServiceCodeField = value;
                    this.RaisePropertyChanged("ServiceCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceName {
            get {
                return this.ServiceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceNameField, value) != true)) {
                    this.ServiceNameField = value;
                    this.RaisePropertyChanged("ServiceName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.StartTimeField, value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatusID {
            get {
                return this.StatusIDField;
            }
            set {
                if ((this.StatusIDField.Equals(value) != true)) {
                    this.StatusIDField = value;
                    this.RaisePropertyChanged("StatusID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationFailure", Namespace="http://schemas.datacontract.org/2004/07/Oac.IntegrationService.Contracts.Faults")]
    [System.SerializableAttribute()]
    public partial class AuthenticationFailure : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IssueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Issue {
            get {
                return this.IssueField;
            }
            set {
                if ((object.ReferenceEquals(this.IssueField, value) != true)) {
                    this.IssueField = value;
                    this.RaisePropertyChanged("Issue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConnectionFailure", Namespace="http://schemas.datacontract.org/2004/07/Oac.IntegrationService.Contracts.Faults")]
    [System.SerializableAttribute()]
    public partial class ConnectionFailure : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IssueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Issue {
            get {
                return this.IssueField;
            }
            set {
                if ((object.ReferenceEquals(this.IssueField, value) != true)) {
                    this.IssueField = value;
                    this.RaisePropertyChanged("Issue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NoDataFound", Namespace="http://schemas.datacontract.org/2004/07/Oac.IntegrationService.Contracts.Faults")]
    [System.SerializableAttribute()]
    public partial class NoDataFound : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IssueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Issue {
            get {
                return this.IssueField;
            }
            set {
                if ((object.ReferenceEquals(this.IssueField, value) != true)) {
                    this.IssueField = value;
                    this.RaisePropertyChanged("Issue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OacIntegrationService.IAppointments")]
    public interface IAppointments {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointments/GetAppointmentsForOLTIntegration", ReplyAction="http://tempuri.org/IAppointments/GetAppointmentsForOLTIntegrationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.OacIntegrationService.AuthenticationFailure), Action="http://tempuri.org/IAppointments/GetAppointmentsForOLTIntegrationAuthenticationFa" +
            "ilureFault", Name="AuthenticationFailure", Namespace="http://schemas.datacontract.org/2004/07/Oac.IntegrationService.Contracts.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.OacIntegrationService.ConnectionFailure), Action="http://tempuri.org/IAppointments/GetAppointmentsForOLTIntegrationConnectionFailur" +
            "eFault", Name="ConnectionFailure", Namespace="http://schemas.datacontract.org/2004/07/Oac.IntegrationService.Contracts.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.OacIntegrationService.NoDataFound), Action="http://tempuri.org/IAppointments/GetAppointmentsForOLTIntegrationNoDataFoundFault" +
            "", Name="NoDataFound", Namespace="http://schemas.datacontract.org/2004/07/Oac.IntegrationService.Contracts.Faults")]
        System.Collections.Generic.List<ConsoleApplication1.OacIntegrationService.Appointment> GetAppointmentsForOLTIntegration(System.DateTime start, System.DateTime end, System.Nullable<System.DateTime> lastUpdated, string accessCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointments/GetAppointmentsForOLTIntegration", ReplyAction="http://tempuri.org/IAppointments/GetAppointmentsForOLTIntegrationResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ConsoleApplication1.OacIntegrationService.Appointment>> GetAppointmentsForOLTIntegrationAsync(System.DateTime start, System.DateTime end, System.Nullable<System.DateTime> lastUpdated, string accessCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointments/CheckIn", ReplyAction="http://tempuri.org/IAppointments/CheckInResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.OacIntegrationService.NoDataFound), Action="http://tempuri.org/IAppointments/CheckInNoDataFoundFault", Name="NoDataFound", Namespace="http://schemas.datacontract.org/2004/07/Oac.IntegrationService.Contracts.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.OacIntegrationService.AuthenticationFailure), Action="http://tempuri.org/IAppointments/CheckInAuthenticationFailureFault", Name="AuthenticationFailure", Namespace="http://schemas.datacontract.org/2004/07/Oac.IntegrationService.Contracts.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.OacIntegrationService.ConnectionFailure), Action="http://tempuri.org/IAppointments/CheckInConnectionFailureFault", Name="ConnectionFailure", Namespace="http://schemas.datacontract.org/2004/07/Oac.IntegrationService.Contracts.Faults")]
        bool CheckIn(int appointmentID, string accessCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointments/CheckIn", ReplyAction="http://tempuri.org/IAppointments/CheckInResponse")]
        System.Threading.Tasks.Task<bool> CheckInAsync(int appointmentID, string accessCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointments/NoShow", ReplyAction="http://tempuri.org/IAppointments/NoShowResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.OacIntegrationService.AuthenticationFailure), Action="http://tempuri.org/IAppointments/NoShowAuthenticationFailureFault", Name="AuthenticationFailure", Namespace="http://schemas.datacontract.org/2004/07/Oac.IntegrationService.Contracts.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.OacIntegrationService.ConnectionFailure), Action="http://tempuri.org/IAppointments/NoShowConnectionFailureFault", Name="ConnectionFailure", Namespace="http://schemas.datacontract.org/2004/07/Oac.IntegrationService.Contracts.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.OacIntegrationService.NoDataFound), Action="http://tempuri.org/IAppointments/NoShowNoDataFoundFault", Name="NoDataFound", Namespace="http://schemas.datacontract.org/2004/07/Oac.IntegrationService.Contracts.Faults")]
        bool NoShow(int appointmentID, string accessCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointments/NoShow", ReplyAction="http://tempuri.org/IAppointments/NoShowResponse")]
        System.Threading.Tasks.Task<bool> NoShowAsync(int appointmentID, string accessCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAppointmentsChannel : ConsoleApplication1.OacIntegrationService.IAppointments, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AppointmentsClient : System.ServiceModel.ClientBase<ConsoleApplication1.OacIntegrationService.IAppointments>, ConsoleApplication1.OacIntegrationService.IAppointments {
        
        public AppointmentsClient() {
        }
        
        public AppointmentsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AppointmentsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AppointmentsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AppointmentsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<ConsoleApplication1.OacIntegrationService.Appointment> GetAppointmentsForOLTIntegration(System.DateTime start, System.DateTime end, System.Nullable<System.DateTime> lastUpdated, string accessCode) {
            return base.Channel.GetAppointmentsForOLTIntegration(start, end, lastUpdated, accessCode);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ConsoleApplication1.OacIntegrationService.Appointment>> GetAppointmentsForOLTIntegrationAsync(System.DateTime start, System.DateTime end, System.Nullable<System.DateTime> lastUpdated, string accessCode) {
            return base.Channel.GetAppointmentsForOLTIntegrationAsync(start, end, lastUpdated, accessCode);
        }
        
        public bool CheckIn(int appointmentID, string accessCode) {
            return base.Channel.CheckIn(appointmentID, accessCode);
        }
        
        public System.Threading.Tasks.Task<bool> CheckInAsync(int appointmentID, string accessCode) {
            return base.Channel.CheckInAsync(appointmentID, accessCode);
        }
        
        public bool NoShow(int appointmentID, string accessCode) {
            return base.Channel.NoShow(appointmentID, accessCode);
        }
        
        public System.Threading.Tasks.Task<bool> NoShowAsync(int appointmentID, string accessCode) {
            return base.Channel.NoShowAsync(appointmentID, accessCode);
        }
    }
}
